version: 2
updates:
  - package-ecosystem: maven
    directory: "/notification-service"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/payment-service"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/reservation-service"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
